import type { Dossier, DossierFile, Finding } from '../types/models'

export const MOCK_DOSSIER: Dossier = {
  id: 'demo-001',
  name: 'Muster Verpackungen GmbH - GDPdU Export 2025',
  status: 'complete',
  file_count: 42,
  record_count: 8547,
  finding_count: 4,
  created_at: '2026-07-18T10:00:00Z',
}

export const MOCK_FILES: DossierFile[] = [
  { file_id: 'f01', relative_path: 'Sachkonten/Sachkontobuchungen.txt', original_name: 'Sachkontobuchungen.txt', extension: '.txt', mime_type: 'text/plain', size_bytes: 4_600_000, classification: 'evidence', parse_status: 'parsed', normalized_record_count: 5200 },
  { file_id: 'f02', relative_path: 'Sachkonten/Sachkonten.txt', original_name: 'Sachkonten.txt', extension: '.txt', mime_type: 'text/plain', size_bytes: 12_400, classification: 'evidence', parse_status: 'parsed', normalized_record_count: 180 },
  { file_id: 'f03', relative_path: 'Kreditoren/Lieferantenbuchungen.txt', original_name: 'Lieferantenbuchungen.txt', extension: '.txt', mime_type: 'text/plain', size_bytes: 301_166, classification: 'evidence', parse_status: 'parsed', normalized_record_count: 1234 },
  { file_id: 'f04', relative_path: 'Kreditoren/Lieferanten.txt', original_name: 'Lieferanten.txt', extension: '.txt', mime_type: 'text/plain', size_bytes: 8_500, classification: 'evidence', parse_status: 'parsed', normalized_record_count: 45 },
  { file_id: 'f05', relative_path: 'Debitoren/Kundenbuchungen.txt', original_name: 'Kundenbuchungen.txt', extension: '.txt', mime_type: 'text/plain', size_bytes: 180_000, classification: 'evidence', parse_status: 'parsed', normalized_record_count: 890 },
  { file_id: 'f06', relative_path: 'Debitoren/Kunden.txt', original_name: 'Kunden.txt', extension: '.txt', mime_type: 'text/plain', size_bytes: 6_200, classification: 'evidence', parse_status: 'parsed', normalized_record_count: 32 },
  { file_id: 'f07', relative_path: 'AV/Anlagen.txt', original_name: 'Anlagen.txt', extension: '.txt', mime_type: 'text/plain', size_bytes: 15_000, classification: 'evidence', parse_status: 'parsed', normalized_record_count: 62 },
  { file_id: 'f08', relative_path: 'AV/Anlagenbuchungen.txt', original_name: 'Anlagenbuchungen.txt', extension: '.txt', mime_type: 'text/plain', size_bytes: 28_000, classification: 'evidence', parse_status: 'parsed', normalized_record_count: 145 },
  { file_id: 'f09', relative_path: 'Begleitdokumente/Wareneingangsliste_2025.csv', original_name: 'Wareneingangsliste_2025.csv', extension: '.csv', mime_type: 'text/csv', size_bytes: 45_000, classification: 'supporting', parse_status: 'parsed', normalized_record_count: 320 },
  { file_id: 'f10', relative_path: 'Begleitdokumente/Stammdatenaenderungen_2025.csv', original_name: 'Stammdatenaenderungen_2025.csv', extension: '.csv', mime_type: 'text/csv', size_bytes: 12_000, classification: 'supporting', parse_status: 'parsed', normalized_record_count: 85 },
  { file_id: 'f11', relative_path: 'Begleitdokumente/Berechtigungsauswertung_2025.xlsx', original_name: 'Berechtigungsauswertung_2025.xlsx', extension: '.xlsx', mime_type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', size_bytes: 22_000, classification: 'supporting', parse_status: 'parsed', normalized_record_count: 28 },
  { file_id: 'f12', relative_path: 'Begleitdokumente/Pruefungsplanung_JET_2025.docx', original_name: 'Pruefungsplanung_JET_2025.docx', extension: '.docx', mime_type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', size_bytes: 35_000, classification: 'supporting', parse_status: 'parsed', normalized_record_count: 12 },
  { file_id: 'f13', relative_path: 'Begleitdokumente/Fakturajournal_Januar_2026_Kreditoren.csv', original_name: 'Fakturajournal_Januar_2026_Kreditoren.csv', extension: '.csv', mime_type: 'text/csv', size_bytes: 18_000, classification: 'supporting', parse_status: 'parsed', normalized_record_count: 95 },
  { file_id: 'f14', relative_path: 'index.xml', original_name: 'index.xml', extension: '.xml', mime_type: 'application/xml', size_bytes: 8_900, classification: 'technical_metadata', parse_status: 'parsed', normalized_record_count: 0 },
  { file_id: 'f15', relative_path: 'gdpdu-01-08-2002.dtd', original_name: 'gdpdu-01-08-2002.dtd', extension: '.dtd', mime_type: 'application/xml-dtd', size_bytes: 3_200, classification: 'technical_metadata', parse_status: 'skipped', normalized_record_count: 0 },
]

export const MOCK_FINDINGS: Finding[] = [
  {
    finding_id: 'F1',
    title: 'Potential shell vendor - unsupported consulting payments',
    severity: 'critical',
    category: 'Vendor fraud',
    amount_at_risk: 248_000,
    currency: 'EUR',
    explanation: 'Vendor 209101 (Ratio Consulting GmbH) created mid-year received 5 round consulting invoices totalling €248,000 with no goods receipts. The same user (MV-U05) created, approved, invoiced, and paid the vendor - a complete segregation-of-duties failure.',
    reasoning: 'The vendor was created on 12.05.2025 by user MV-U05 and approved by the same user (no four-eyes principle). Five invoices for "Beratungsleistungen" with round amounts were posted and paid by MV-U05. No matching goods receipts exist in the warehouse receipt log. MV-U05 holds combined permissions for vendor creation, posting, and payment runs - enabling end-to-end fraud without independent oversight.',
    evidence_count: 5,
    confidence: 'High',
    status: 'demo',
    evidence: [
      { evidence_id: 'E1-1', finding_id: 'F1', record_id: 'r-kred-209101-001', document_id: 'f03', label: '5 round consulting invoices to vendor 209101', excerpt: 'KONTO=209101; BUCHUNGSTEXT=Beratungsleistungen; BETRAG=49.600,00 / 50.400,00 / 48.000,00 / 51.200,00 / 48.800,00', source_location: { relative_path: 'Kreditoren/Lieferantenbuchungen.txt', sheet: null, page: null, row_start: 892, row_end: 901, columns: ['KONTO', 'BUCHUNGSTEXT', 'BETRAG'], paragraph: null }, original_language: 'de', explanation_en: 'Five invoices with round amounts totalling €248,000 posted to vendor 209101.' },
      { evidence_id: 'E1-2', finding_id: 'F1', record_id: 'r-stamm-209101', document_id: 'f10', label: 'Vendor created and approved by same user', excerpt: 'AENDERUNGSART=Neuanlage Kreditor; KONTO=209101; GEAENDERT_VON=MV-U05; GENEHMIGT_VON=MV-U05', source_location: { relative_path: 'Begleitdokumente/Stammdatenaenderungen_2025.csv', sheet: null, page: null, row_start: 12, row_end: 12, columns: ['GEAENDERT_VON', 'GENEHMIGT_VON'], paragraph: null }, original_language: 'de', explanation_en: 'The same user MV-U05 both created and approved vendor 209101 - no four-eyes control.' },
      { evidence_id: 'E1-3', finding_id: 'F1', record_id: 'r-ware-missing', document_id: 'f09', label: 'No goods receipts for vendor 209101', excerpt: 'Vendor 209101 absent from Wareneingangsliste_2025.csv', source_location: { relative_path: 'Begleitdokumente/Wareneingangsliste_2025.csv', sheet: null, page: null, row_start: null, row_end: null, columns: null, paragraph: null }, original_language: 'de', explanation_en: 'No goods receipt exists for vendor 209101 - services were never evidenced as delivered.' },
      { evidence_id: 'E1-4', finding_id: 'F1', record_id: 'r-berechtigung-mvu05', document_id: 'f11', label: 'MV-U05 holds incompatible permissions', excerpt: 'BENUTZER=MV-U05; BERECHTIGUNG=Buchen, Zahlungslauf, Kreditor anlegen', source_location: { relative_path: 'Begleitdokumente/Berechtigungsauswertung_2025.xlsx', sheet: 'Berechtigungen', page: null, row_start: 8, row_end: 8, columns: ['BENUTZER', 'BERECHTIGUNG'], paragraph: null }, original_language: 'de', explanation_en: 'User MV-U05 can create vendors, post invoices, and execute payment runs - a critical segregation-of-duties conflict.' },
      { evidence_id: 'E1-5', finding_id: 'F1', record_id: 'r-kred-209101-pay', document_id: 'f03', label: '5 payments to vendor 209101 by MV-U05', excerpt: 'KONTO=209101; BUCHUNGSTYP=Zahlung; ERFASSER=MV-U05', source_location: { relative_path: 'Kreditoren/Lieferantenbuchungen.txt', sheet: null, page: null, row_start: 902, row_end: 906, columns: ['KONTO', 'BUCHUNGSTYP', 'ERFASSER'], paragraph: null }, original_language: 'de', explanation_en: 'All five payments to the suspect vendor were executed by the same user who created it.' },
    ],
  },
  {
    finding_id: 'F2',
    title: 'Repairs potentially capitalized as fixed assets',
    severity: 'high',
    category: 'Asset misstatement',
    amount_at_risk: 150_800,
    currency: 'EUR',
    explanation: 'Six repair/maintenance items totalling €150,800 net were booked as asset additions (accounts 040000/060000) instead of repair expense account 670000. This overstates both assets and profit.',
    reasoning: 'Asset records contain items with repair-type names ("Reparatur Konfektioniermaschine", "Austausch Hydraulikaggregat", "Generalueberholung") that should be expensed. The corresponding postings debit fixed-asset accounts rather than expense account 670000 "Instandhaltung und Reparaturen". The net effect inflates reported assets and understates expenses by €150,800.',
    evidence_count: 3,
    confidence: 'High',
    status: 'demo',
    evidence: [
      { evidence_id: 'E2-1', finding_id: 'F2', record_id: 'r-av-repairs', document_id: 'f07', label: '6 repair-named asset records', excerpt: 'BEZEICHNUNG contains "Reparatur|Instandsetzung|Austausch|Generalueberholung"; KONTO=040000/060000', source_location: { relative_path: 'AV/Anlagen.txt', sheet: null, page: null, row_start: 34, row_end: 39, columns: ['BEZEICHNUNG', 'KONTO'], paragraph: null }, original_language: 'de', explanation_en: 'Six assets with repair-type names were capitalized in fixed-asset classes rather than expensed.' },
      { evidence_id: 'E2-2', finding_id: 'F2', record_id: 'r-av-buchungen', document_id: 'f08', label: 'Acquisition postings to asset accounts', excerpt: 'BUCHUNGSART=Zugang; KONTO=040000; BETRAG=150.800,00 net total', source_location: { relative_path: 'AV/Anlagenbuchungen.txt', sheet: null, page: null, row_start: 78, row_end: 83, columns: ['BUCHUNGSART', 'KONTO', 'BETRAG'], paragraph: null }, original_language: 'de', explanation_en: 'The repair costs were posted as asset acquisitions rather than to expense account 670000.' },
      { evidence_id: 'E2-3', finding_id: 'F2', record_id: 'r-sachkonto-670', document_id: 'f01', label: 'No matching expense in account 670000', excerpt: 'Account 670000 "Instandhaltung und Reparaturen" has no entries for these repair items', source_location: { relative_path: 'Sachkonten/Sachkontobuchungen.txt', sheet: null, page: null, row_start: null, row_end: null, columns: ['KONTO'], paragraph: null }, original_language: 'de', explanation_en: 'The proper repair expense account shows no corresponding entries for these items.' },
    ],
  },
  {
    finding_id: 'F3',
    title: 'December costs posted in January without accrual',
    severity: 'high',
    category: 'Cut-off error',
    amount_at_risk: 192_000,
    currency: 'EUR',
    explanation: 'Eight supplier invoices for December 2025 deliveries (€192,000 net) were booked in January 2026 without a year-end accrual. Matching December goods receipts confirm the services were received in 2025. This overstates 2025 profit.',
    reasoning: 'The January 2026 invoice journal shows 8 invoices with December 2025 service dates. The goods receipt list confirms December deliveries marked "Rechnung offen" (invoice pending). No accrual (Rueckstellung/Verbindlichkeit) was posted in December 2025 for these items. Other December unbilled items were correctly accrued, making this omission the anomaly.',
    evidence_count: 4,
    confidence: 'High',
    status: 'demo',
    evidence: [
      { evidence_id: 'E3-1', finding_id: 'F3', record_id: 'r-faktura-jan', document_id: 'f13', label: '8 January invoices with December service dates', excerpt: 'FAKTURADATUM=Jan 2026; LEISTUNGSDATUM=Dez 2025; 8 invoices totalling EUR 192,000', source_location: { relative_path: 'Begleitdokumente/Fakturajournal_Januar_2026_Kreditoren.csv', sheet: null, page: null, row_start: 5, row_end: 12, columns: ['FAKTURADATUM', 'LEISTUNGSDATUM', 'BETRAG'], paragraph: null }, original_language: 'de', explanation_en: 'Eight invoices dated January 2026 reference December 2025 service periods.' },
      { evidence_id: 'E3-2', finding_id: 'F3', record_id: 'r-ware-dec', document_id: 'f09', label: 'Matching December goods receipts marked open', excerpt: 'WARENEINGANGSDATUM=Dez 2025; STATUS=Rechnung offen', source_location: { relative_path: 'Begleitdokumente/Wareneingangsliste_2025.csv', sheet: null, page: null, row_start: 280, row_end: 287, columns: ['WARENEINGANGSDATUM', 'STATUS'], paragraph: null }, original_language: 'de', explanation_en: 'Goods were received in December 2025 with invoices still open at year-end.' },
      { evidence_id: 'E3-3', finding_id: 'F3', record_id: 'r-sachkonto-no-accrual', document_id: 'f01', label: 'No 2025 accrual for these items', excerpt: 'No Rueckstellung or Verbindlichkeit posting in Dec 2025 for the 8 vendors/amounts', source_location: { relative_path: 'Sachkonten/Sachkontobuchungen.txt', sheet: null, page: null, row_start: null, row_end: null, columns: ['BUCHUNGSTEXT', 'KONTO'], paragraph: null }, original_language: 'de', explanation_en: 'No year-end provision was posted for these known December liabilities.' },
      { evidence_id: 'E3-4', finding_id: 'F3', record_id: 'r-sachkonto-legit-accrual', document_id: 'f01', label: 'Other December accruals were posted correctly', excerpt: 'BUCHUNGSTEXT=Rueckstellung unfakturierte Leistungen Dez 2025; BETRAG=86.500,00', source_location: { relative_path: 'Sachkonten/Sachkontobuchungen.txt', sheet: null, page: null, row_start: 4850, row_end: 4850, columns: ['BUCHUNGSTEXT', 'BETRAG'], paragraph: null }, original_language: 'de', explanation_en: 'A legitimate €86,500 accrual proves the company knows the process - making the omission on these 8 items anomalous.' },
    ],
  },
  {
    finding_id: 'F4',
    title: 'Payments potentially split below approval threshold',
    severity: 'medium',
    category: 'Control circumvention',
    amount_at_risk: 39_040,
    currency: 'EUR',
    explanation: 'Four payments to vendor 200007 (Castor Papier GmbH) on 14.10.2025, each just below €10,000, totalling €39,040. The documented approval threshold is €10,000 for two-signature requirement.',
    reasoning: 'The general ledger shows four payment entries on the same date to the same vendor, each narrowly below the €10,000 threshold (€9,780 / €9,820 / €9,750 / €9,690). The audit planning document confirms the €10,000 two-signature requirement. Splitting payments to avoid dual authorization is a classic control circumvention pattern.',
    evidence_count: 3,
    confidence: 'Medium',
    status: 'demo',
    evidence: [
      { evidence_id: 'E4-1', finding_id: 'F4', record_id: 'r-sachkonto-split', document_id: 'f01', label: '4 payments just under EUR 10,000 on same date', excerpt: 'KONTO=200007; DATUM=14.10.2025; BUCHUNGSTYP=Zahlung; BETRAG=9.780/9.820/9.750/9.690; BELEGNR=SAMMEL-200007', source_location: { relative_path: 'Sachkonten/Sachkontobuchungen.txt', sheet: null, page: null, row_start: 3200, row_end: 3203, columns: ['KONTO', 'DATUM', 'BETRAG', 'BELEGNR'], paragraph: null }, original_language: 'de', explanation_en: 'Four payments on 14.10.2025 to vendor 200007, each just below the €10,000 threshold.' },
      { evidence_id: 'E4-2', finding_id: 'F4', record_id: 'r-pruefung-threshold', document_id: 'f12', label: 'EUR 10,000 approval threshold documented', excerpt: 'Freigabegrenze: EUR 10.000 (Zwei-Unterschriften-Regelung)', source_location: { relative_path: 'Begleitdokumente/Pruefungsplanung_JET_2025.docx', sheet: null, page: 3, row_start: null, row_end: null, columns: null, paragraph: 8 }, original_language: 'de', explanation_en: 'The audit planning document states the €10,000 two-signature approval threshold.' },
      { evidence_id: 'E4-3', finding_id: 'F4', record_id: 'r-sachkonto-split-total', document_id: 'f01', label: 'Combined amount EUR 39,040 exceeds threshold', excerpt: 'Sum of 4 payments: 9.780 + 9.820 + 9.750 + 9.690 = 39.040 EUR', source_location: { relative_path: 'Sachkonten/Sachkontobuchungen.txt', sheet: null, page: null, row_start: 3200, row_end: 3203, columns: ['BETRAG'], paragraph: null }, original_language: 'de', explanation_en: 'The combined €39,040 is nearly 4x the threshold, indicating intentional splitting.' },
    ],
  },
]
